
- name: Build and push Docker image
  hosts: all

  vars:
    image_name: glad47/my-app
    image_tag: latest
  tasks:
    - name: Show debug message before building
      debug:
        msg: "Build Docker image"

    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: /var/lib/awx/projects/ssh/hello-world-pipeline"

    - name: Show debug message before pushing
      debug:
        msg: "Push Docker image"

    - name: Push Docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: true

