- name: Build and push simple-web Docker image using command line
  hosts: localhost
  gather_facts: false
  vars:
    image_name: simple-web
    image_tag: latest
    docker_registry: "{{ lookup('env', 'REGISTRY_URL') }}"  # Now clearly named
    docker_namespace: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
    full_image_name: "{{ docker_registry }}/{{ docker_namespace }}/{{ image_name }}:{{ image_tag }}"

  tasks:
    - name: 🐳 Build Docker image
      shell: |
        docker build -t {{ image_name }}:{{ image_tag }} /opt/projects/hello-world-pipeline

    - name: 🏷️ Tag Docker image for remote registry
      shell: |
        docker tag {{ image_name }}:{{ image_tag }} {{ full_image_name }}

    - name: 🔐 Login to Docker registry
      shell: |
        echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY_URL" -u "$REGISTRY_USERNAME" --password-stdin
      environment:
        REGISTRY_USERNAME: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
        REGISTRY_PASSWORD: "{{ lookup('env', 'REGISTRY_PASSWORD') }}"
        REGISTRY_URL: "{{ docker_registry }}"
      no_log: true

    - name: 📤 Push Docker image to registry
      shell: |
        docker push {{ full_image_name }}
