---
- name: Test rootless Docker with hello-world
  hosts: localhost
  gather_facts: false
  tasks:

    - name: "⏸ Simulate container pause for one day"
      shell: sleep 86400
      args:
        executable: /bin/bash
