---
- name: Run hello-world container using Docker CLI
  hosts: localhost
  become: true
  tasks:

    - name: Ensure Docker is installed
      package:
        name: docker
        state: present

    - name: Run hello-world container
      command: docker run --rm hello-world
      register: hello_output
      changed_when: false  # Because docker run --rm always exits cleanly
      failed_when: hello_output.rc != 0

    - name: Show container output
      debug:
        var: hello_output.stdout

