---
- name: 🐳 Build custom image from hello-world using Docker
  hosts: localhost
  gather_facts: false
  become: true
  tasks:

    - name: 📁 Create build directory
      file:
        path: /tmp/hello-world-image
        state: directory

    - name: 📝 Write a basic Dockerfile
      copy:
        dest: /tmp/hello-world-image/Dockerfile
        content: |
          FROM hello-world

    - name: 🛠️ Build image using Docker
      shell: sudo podman build -t custom-hello-world /tmp/hello-world-image
      register: build_output

    - name: 📋 Show build logs
      debug:
        var: build_output.stdout_lines
