---
- name: Run hello-world container with Docker (Ansible way)
  hosts: localhost
  become: true
  collections:
    - community.docker
  tasks:

    - name: Ensure Docker is installed
      package:
        name: docker
        state: present

    - name: Run hello-world container
      docker_container:
        name: hello
        image: hello-world
        state: started
        auto_remove: true
      register: hello_result

    - name: Show container output
      debug:
        var: hello_result.container.Output
