---
- name: Run hello-world container using Podman
  hosts: localhost
  become: true
  tasks:

    - name: Ensure Podman is installed
      package:
        name: podman
        state: present

    - name: Run hello-world container
      command: podman run --rm hello-world
      register: hello_output

    - name: Show container output
      debug:
        var: hello_output.stdout


   