---
- name: Run hello-world container with Podman (Ansible way)
  hosts: localhost
  become: true
  collections:
    - containers.podman
  tasks:

    - name: Ensure Podman is installed
      package:
        name: podman
        state: present

    - name: Run hello-world container
      podman_container:
        name: hello
        image: hello-world
        state: started
        rm: true
      register: hello_result

    - name: Show container output
      debug:
        var: hello_result.stdout

   