---
- name: 🐧 Run hello-world with Podman
  hosts: localhost
  gather_facts: false
  become: true
  tasks:

    - name: 🐳 Run hello-world container using Podman
      shell: sudo podman run --rm hello-world
      register: hello_output

    - name: 🎉 Show hello-world output
      debug:
        var: hello_output.stdout_lines
