---
- name: 🐳 Build custom image from hello-world using Docker
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: 📦 List all pods in the 'awx' namespace
      shell: kubectl get pods -A
      register: awx_pods

    - name: 📋 Show AWX pod list
      debug:
        var: awx_pods.stdout_lines
   